stages:
- name: repo-update
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world-v1
      registry: 127.0.0.1:34059
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
