stages:
- name: Build something
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: date -R
  when:
    branch:
      include:
      - master
    event: {}
- name: Publish my image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ichetanbhatt/test-repo:latest
      pushRemote: true
      registry: index.docker.io
notification: {}
