stages:
- name: repo-update
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world-v1
      pushRemote: true
      registry: registry.o4s.in:8081
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
