stages:
- name: repo-update
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world
      pushRemote: true
      registry: localhost:5000
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
