stages:
- name: Build something
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: date -R
  when:
    branch:
      include:
      - master
    event: {}
- name: Publish my image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ichetanbhatt/test-repo:latest
      pushRemote: true
      registry: index.docker.io
- name: Redeploy
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: 'curl -u "token-bhnsj:dxbkwxclj6dtw2kh4qcdffnxxjmgm9mf8dkfp97xsc7rdqszkxvjsc"
        -X POST -H ''Accept: application/json'' -H ''Content-Type: application/json''
        ''https://192.168.1.21:8443/v3/project/c-qdr9f:p-czkd6/workloads/deployment:dev:hello-world?action=redeploy''
        --insecure'
notification: {}
