stages:
- name: repo-update
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world-v1
      pushRemote: true
      registry: 192.168.1.21:5000
    env:
    PLUGIN_DEBUG: "true"
    PLUGIN_INSECURE: "true"
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
