stages:
- name: Publish my image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ichetanbhatt/test-repo:v1.0
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include:
      - master
    event:
      include:
      - push