stages:
- name: Build something
  # Conditions for stages
  when:
    branch: master
    event: [ push ]
  # Multiple steps run concurrently
  steps:
    - runScriptConfig:
        image: busybox
        shellScript: date -R
- name: Publish my image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ichetanbhatt/test-repo:latest
      # Optionally push to remote registry
      pushRemote: true
      registry: index.docker.io