stages:
- name: repo-update
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        docker login -u admin -p admin@123 http://registry.o4s.in:8081/
        echo done
  when:
    event:
      include:
      - push
notification: {}
